apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: nodejs-ilcjjszk
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/nodejs-ilcjjszk:abb22449b47d36f6b2b69c1f85f41138e33a9737@sha256:45ee8e8812756feb0148c4b1eeaeecb71fa8a448ecd036d911005ca20c77547d
        name: container-image  
